Breaking changes for v3.0.0 (#108)
* removed childrelationshipservice

* removing deprecated MockDml methods

* removing deprecated methods from Soql class

* fixing ci -- adding command to clean up expired scratch orgs

* fixing echo issue

* contd.

* contd.

* contd.

* trying logout

* contd.

* debugging

* trying another approach

* removing sf org list --clean

* ci fixes

* contd.

* contd.

* stupid

* cleanup

* ignore flow engine for sf scanner

* formally adding sfca to package

* fixing @SuppressWarnings issue - whitespace

* checkpoint - squashing violations

* checkpoint - solved most issues

* reverting files that should not have changed

* downgrade 'AvoidBooleanMethodParameters' rule severity

* adding AvoidBooleanMethodParameters to suppresswarnings

* removing rule downgrades; i'll just suppress them individually

* minimizing suppression at top level

* oh, we can implement sharing on inner classes now?

* trialing custom sfca action

* remove extraneous error handling step

* removing lfs

* install latest version of plugins

* fixing eslint violation

* re-adding GH_TOKEN

* added suppresswarnings for boolean parameters

* prepping for managed package

* adding ready_for_review event to ci job

* creating managed package

* removing salesforce-packages directory...for now

* converted docs to use ApexDoc

* "Claude PR Assistant workflow"

* "Claude Code Review workflow"

* fixing violations

* contd.

* ran prettier

* contd.

* fixed all violations

* moving claude review action into ci.yml

* give code review action a name

* fixing review comments

* light fixes

* added code coverage check to ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,7 +6,7 @@ on:
       - main
     paths:
       - "force-app/**"
-    types: [opened, reopened, synchronize]
+    types: [opened, ready_for_review, reopened, synchronize]
 
 concurrency:
   # Cancel old runs when a new commit is pushed to the same branch
@@ -15,14 +15,49 @@ concurrency:
 
 env:
   CHANGES_DIR: changes
+  SCRATCH_ORG_DOMAIN: apex-database-layer.com
+  GH_TOKEN: ${{ github.token }}
+  PR_NUMBER: ${{ github.event.pull_request.number }}
+  SCAN_OUTPUTS: results.txt
+  SCAN_SUMMARY: summary.md
+  SFCA_RESULTS: sf-code-analyzer-results.json
 
 permissions:
   actions: read
   contents: read
+  id-token: write
   issues: write
   pull-requests: write
 
 jobs:
+  claude-review:
+    name: Claude Code Review
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: read
+      issues: read
+      id-token: write
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
+
+      - name: Run Claude Code Review
+        id: claude-review
+        uses: anthropics/claude-code-action@beta
+        with:
+          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
+          direct_prompt: |
+            Please review this pull request and provide feedback on:
+            - Code quality and best practices
+            - Potential bugs or issues
+            - Performance considerations
+            - Security concerns
+            - Test coverage
+
   scan:
     name: Run Static Analysis
     if: ${{ '! github.event.pull_request.draft' }}
@@ -48,21 +83,41 @@ jobs:
           echo "Changed files:"
           ls "$CHANGES_DIR"
 
-      - name: Run Salesforce Code Analyzer
+      - name: Scan
         id: scan
-        uses: forcedotcom/run-code-analyzer@v2
-        with:
-          github-token: ${{ github.token }}
-          results-artifact-name: salesforce-code-analyzer-results
-          run-arguments: "--target ${{ env.CHANGES_DIR }} --view detail --output-file sfca_results.json"
-
-      - name: Evaluate
-        if: |
-          steps.scan.outputs.exit-code > 0 ||
-          steps.scan.outputs.num-sev1-violations > 0 ||
-          steps.scan.outputs.num-sev2-violations > 0
         run: |
-          echo "🚨 sf code-analyzer detected violations that exceed the acceptable threshold."
+          # Perform the scanning logic, via a .py script that creates various artifacts:
+          export PATH="$HOME/sf/bin:$PATH"
+          python3 .github/scripts/static_analysis.py \
+            --results-file "$SCAN_OUTPUTS" \
+            --sfca-output-file "$SFCA_RESULTS" \
+            --summary-file "$SCAN_SUMMARY" \
+            --target "$CHANGES_DIR" \
+            --threshold 5
+          # Save the output variables to be referenced in later steps:
+          cat "$SCAN_OUTPUTS" >> $GITHUB_OUTPUT
+
+      - name: Summarize
+        run: |
+          # Add the .md Summary to a PR Review, and the Step Summary;
+          SUMMARY=$(cat "$SCAN_SUMMARY")
+          echo "$SUMMARY" >> "$GITHUB_STEP_SUMMARY"
+          gh pr review "$PR_NUMBER" --body "$SUMMARY" --comment
+
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: Raw Results
+          path: |
+            ${{ env.SFCA_RESULTS }}
+
+      - name: Report Violations
+        if: ${{ steps.scan.outputs.num-violations-above-threshold > 0 }}
+        run: |
+          # If any violations above the specified threshold, post the results to the PR and fail the check:
+          NUM_VIOLATIONS=${{ steps.scan.outputs.num-violations-above-threshold}}
+          echo "⚠️ Detected $NUM_VIOLATIONS violations that meet/exceed the set threshold. View the job summary for more details:"
+          echo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
           exit 1
 
   run-unit-tests:
@@ -91,14 +146,6 @@ jobs:
             --set-default-dev-hub \
             --username "$USERNAME"
 
-      - name: Generate Username
-        id: generate-username
-        run: |
-          # Dynamically generate a scratch org username, based on the repository
-          USERNAME="${GITHUB_REPOSITORY##*/}-ci@${GITHUB_REPOSITORY%%/*}.com"
-          echo "username=$USERNAME" >> "$GITHUB_OUTPUT"
-          echo "Scratch Org Username: $USERNAME"
-
       - name: Get Existing Scratch Org
         id: get-existing
         continue-on-error: true
@@ -106,15 +153,17 @@ jobs:
           CLIENT_ID: ${{ secrets.SALESFORCE_CONSUMER_KEY }}
           DEV_HUB: ${{ secrets.SALESFORCE_DEVHUB_USERNAME }}
           JWT_KEY: ${{ secrets.SALESFORCE_JWT_KEY }}
-          USERNAME: ${{ steps.generate-username.outputs.username }}
         run: |
           # Re-use scratch orgs to prevent exceeding new scratch orgs/day limits:
           set -euo pipefail
-          QUERY="SELECT LoginUrl FROM ScratchOrgInfo WHERE SignupUsername = '$USERNAME'"
+          QUERY="SELECT LoginUrl, SignupUsername FROM ScratchOrgInfo WHERE SignupUsername LIKE '%$SCRATCH_ORG_DOMAIN' AND Status = 'Active'"
+          echo "$QUERY"
           RESPONSE=$(sf data query --target-org "$DEV_HUB" -q "$QUERY" --json 2>/dev/null || true)
+          echo "$RESPONSE"
           LOGIN_URL=$(echo "$RESPONSE" | jq -r '.result.records[0]?.LoginUrl // empty')
-          echo "Existing Scratch Org: $LOGIN_URL"
-          if [[ -n "$LOGIN_URL" && "$LOGIN_URL" != "null" ]]; then
+          USERNAME=$(echo "$RESPONSE" | jq -r '.result.records[0]?.SignupUsername // empty')
+          if [[ -n "$USERNAME" && "$USERNAME" != "null" ]]; then
+            echo "Signing into scratch org with username $USERNAME..."
             sf org login jwt \
               --client-id "$CLIENT_ID" \
               --instance-url "$LOGIN_URL" \
@@ -126,29 +175,39 @@ jobs:
 
       - name: Create Scratch Org
         if: ${{ steps.get-existing.outputs.success != 'true' }}
-        env:
-          USERNAME: ${{ steps.generate-username.outputs.username }}
         run: |
+          # Create a new scratch org, with a dynamic username ending in the repo's domain:
           set -euo pipefail
+          DATE=$(date +%y%m%d)
+          USERNAME="$DATE-ci@$SCRATCH_ORG_DOMAIN"
+          echo "Creating scratch org with username $USERNAME..."
           sf org create scratch \
             --definition-file config/project-scratch-def.json \
-            --duration-days 1 \
+            --duration-days 2 \
             --set-default \
             --username "$USERNAME" \
             --wait 10
 
       - name: Run Tests
-        env:
-          SCRATCH_ORG: ${{ steps.generate-username.outputs.username }}
         run: |
           sf project deploy start \
+            --coverage-formatters json-summary \
             --dry-run \
             --ignore-conflicts \
             --source-dir force-app \
-            --target-org "$SCRATCH_ORG" \
             --test-level RunLocalTests \
             --verbose \
             --wait 30
+
+      - name: Check Code Coverage
+        run: |
+          # Parse the JSON coverage summary file to extract overall coverage percentage
+          COVERAGE_PERCENT=$(cat coverage/coverage/coverage-summary.json | jq -r '.total.lines.pct')
+          echo "Code coverage: ${COVERAGE_PERCENT}%"
+          if [ "$COVERAGE_PERCENT" != "100" ]; then
+            echo "❌ Code coverage is ${COVERAGE_PERCENT}%, but 100% is required"
+            exit 1
+          fi
 
       - name: Post Authenticate Devhub
         if: ${{ always() }}
